[package]
name = "tano-watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
tano-macro = { path = "../tano-macro", version = "0.1.0" }
tano-shared = { path = "../tano-shared", version = "0.1.0" }
tano-providers = { path = "../tano-providers", version = "0.1.0" }
color-eyre = "0.6.5"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
bitflags = "2.13.1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"

[target.'cfg(target_os = "macos")'.dependencies]
dispatch2 = "0.3.1"
objc2-core-foundation = "0.3.2"
objc2-core-services = { version = "0.3.2", features = ["FSEvents"] }
