[package]
name = "tano-shared"
description = "Tano shared library"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre = "0.6.5"
directories = "6.0.0"
