[package]
name = "tano-config"
description = "Tano config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tano-shared = { path = "../tano-shared", version = "0.1.0" }
tano-macro = { path = "../tano-macro", version = "0.1.0" }
color-eyre = "0.6.5"
directories = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
toml = "1.1.4"
tracing = "0.1.44"
shellexpand = "3.1.2"
bitflags = "2.13.1"
