provider = [{ type = "local", path = "~/Music/" }]

keymap = [
  { on = "q", run = "quit" },
  { on = "<C-c>", run = "quit" },
  { on = "<C-z>", run = "suspend" },
  { on = "h", run = "left" },
  { on = "<Left>", run = "left" },
  { on = "j", run = "down" },
  { on = "<Down>", run = "down" },
  { on = "k", run = "up" },
  { on = "<Up>", run = "up" },
  { on = "l", run = "right" },
  { on = "<Right>", run = "right" },
  { on = "<C-d>", run = { scroll = "50%" } },
  { on = "<C-u>", run = { scroll = "-50%" } },
  { on = [
    "g",
    "g",
  ], run = "top" },
  { on = "<S-g>", run = "bottom" },
  { on = [
    "g",
    "o",
  ], run = { goto = "overview" } },
  { on = [
    "g",
    "s",
  ], run = { goto = "songs" } },
  { on = [
    "g",
    "a",
  ], run = { goto = "albums" } },
  { on = [
    "g",
    "r",
  ], run = { goto = "artists" } },
]

page.overview.sections = ["songs", "albums", "artists"]
page.album.hide_track_numbers = false
page.album.hide_artists = false

startup_page = "overview"
