[package]
name = "tano-providers"
version = "0.1.0"
edition = "2024"

[dependencies]
tano-config = { path = "../tano-config", version = "0.1.0" }
tano-macro = { path = "../tano-macro", version = "0.1.0" }
tokio = { version = "1.52.3", features = ["full"] }
color-eyre = "0.6.5"
tracing = "0.1.44"
lofty = "0.25.0"
