[package]
name = "tano-providers"
description = "Tano providers"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tano-config = { path = "../tano-config", version = "0.1.0" }
tano-macro = { path = "../tano-macro", version = "0.1.0" }
tokio = { version = "1.52.3", features = ["full"] }
color-eyre = "0.6.5"
tracing = "0.1.44"
lofty = "0.25.0"
