[package]
name = "tano-database"
description = "Tano database"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tano-shared = { path = "../tano-shared", version = "0.1.1" }
tano-providers = { path = "../tano-providers", version = "0.1.1" }
tano-macro = { path = "../tano-macro", version = "0.1.1" }

color-eyre = "0.6.5"
tokio = { version = "1.52.3", features = ["full"] }
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "uuid"] }
