[package]
name = "tano"
description = "A terminal music player"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tano-config = { path = "../tano-config", version = "0.1.1" }
tano-database = { path = "../tano-database", version = "0.1.1" }
tano-tui = { path = "../tano-tui", version = "0.1.1" }
tano-backend = { path = "../tano-backend", version = "0.1.1" }
tano-watcher = { path = "../tano-watcher", version = "0.1.1" }
tano-shared = { path = "../tano-shared", version = "0.1.1" }
tano-macro = { path = "../tano-macro", version = "0.1.1" }
tano-providers = { path = "../tano-providers", version = "0.1.1" }

color-eyre = "0.6.5"
tokio = { version = "1.52.3", features = ["full"] }
crossterm = "0.29.0"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-error = "0.2.1"
